### PR TITLE
Change if to else-if to avoid unnecessary comparison

### PR DESCRIPTION
**Pull request by wbierman**

### CODE REVIEW

**Comment by wbierman** [comment]
I believe the compilation failure listed above with 'AppVeyor' is incorrect.

**Comment by grahamboree** [comment]
Yeah it looks like AppVeyor couldn't spawn a worker to run the VS2010 build, which is why it failed.  I'm not a huge fan of if's and else's without braces; it's inviting a dangling else bug.  Could you add them?

**Comment by wbierman** [comment]
Done.  I replaced the previous commit.  Maybe this time AppVeyor will succeed!

**Comment by grahamboree** [comment]
Thanks!

**Pull request merged**
