### PR TITLE
Several fixes for make install

### PR DESCRIPTION
**Pull request by DarthGandalf**
To make this easier to package

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Perhaps instead of "Don't install DebugDraw.h" it should install every header to /usr/include/recastnavigation ?

**Comment by DarthGandalf** [comment]
I'll answer my question: DebugDraw.h is used by OpenMW, so can't be just deleted...

**Comment by DarthGandalf** [comment]
@jakobbotsch hi?

**Comment by jakobbotsch** [comment]
@DarthGandalf Thank you, sorry for the late reaction!

**Pull request merged**
