### PR TITLE
Camera moves up/down and arrows

### PR DESCRIPTION
**Pull request by domalb**
Camera movements extended : 
- arrows up/left/down/right mimic W/A/S/D
- Q/E and page_up/page_down allow vertical displacement

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Can you please rebase your commits? As you can see there are 17 commits, but only one of them is relevant to the PR.
@grahamboree gave a good way to do it in #254.

Thanks!

**Comment by domalb** [comment]
I tried, God knows that I tried !!! :)
But sorry, Git CLI is just too much pain.
10mn for the feature, 1h for struggling with Git... sorry I'm out of time :(

**Comment by aurelien-rainone** [comment]
@jakobbotsch you can merge and squash now directly from github

**Comment by jakobbotsch** [comment]
@aurelien-rainone Yes, it is a nice feature, but squashing before the PR still helps us maintainers get a quick overview of how the change is split up, and helps with the commit message. With that said I have used the feature on the previous PRs from @domalb and I will do so again, I just don't want the commit lists to keep growing like this.

@domalb The feature looks fine. Thanks!

**Comment by domalb** [comment]
@jakobbotsch thank you for you fixing.
I will try another client to get my branch rebased.

**Pull request merged**
