### PR TITLE
Allow 64 bit windows builds

### PR DESCRIPTION
**Pull request by jarrettchisholm**

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Hi, thank you for this. Sorry for getting to it so very late.

Would you mind updating the AppVeyor build to be 64-bit as well? I don't think we need a 32-bit build, so you can just change it. I believe you just need to add:

```yaml
platform:
  - x64
```

Below `configuration`.

**Comment by jakobbotsch** [comment]
Looks like a couple of explicit casts or type updates are needed:
  c:\projects\recastnavigation\recastdemo\source\sample_tempobstacles.cpp(1342): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\projects\recastnavigation\RecastDemo\Build\vs2017\RecastDemo.vcxproj]
  c:\projects\recastnavigation\recastdemo\source\imgui.cpp(36): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\projects\recastnavigation\RecastDemo\Build\vs2017\RecastDemo.vcxproj]

**Comment by jarrettchisholm** [comment]
Should be fixed now.

**Comment by jakobbotsch** [comment]
Thank you!

**Pull request merged**
