### PR TITLE
Sync version in CMakeLists.txt with last release

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Can we make it 1.5.2 as there has been changes since 1.5.1?

**Comment by jakobbotsch** [comment]
Also cc @elsid, not exactly sure how this affects people who are using this build already.

**Comment by elsid** [comment]
This change shouldn't make any problems. It only changes name of dynamic library file. Proper cmake file can handle this.

**Comment by mimi1vx** [comment]
and this is problem :( so it mixups with `soname`

**Pull request closed without merging**
