### PR TITLE
Poly query API: expose distance and isOverPoly

### PR DESCRIPTION
**Pull request by Bromeon**
The current API `dtNavMeshQuery::findNearerestPoly()` does not allow the caller to get information about:
* whether `center` is actually _on_ a polygon
* what is the distance to the polygon (even if it's _on_ one, this can be vertical distance).

Of course it would be possible for the caller to compute these after the call, however `findNearestPoly()` has the information readily available.

I simply added an overload and didn't de-duplicate code, please let me know if you think such an API makes sense, and what would be the preferred way.

### CODE REVIEW

**Comment by Bromeon** [comment]
Any feedback on this?

**Comment by jakobbotsch** [comment]
Seems reasonable to me. What is the benefit of exposing the distance? It is not exactly euclidean distance, so it might be a bit confusing, and otherwise computing it from the nearest point is trivial since the expensive part is the square root that has to be done anyway.

**Comment by Bromeon** [comment]
@jakobbotsch Thanks for the feedback! Good point about the distance.

If I understand it correctly, it measures:
* the euclidean distance if the point is outside the navmesh's "airspace" (`overPoly == false`, red case)
* the vertical distance **minus walkableClimb** if it's inside (`overPoly == true`, blue case).
grafik

`walkableClimb` being taken into account means that everything that's "within climb reach" of the agent is considered zero distance. So the whole "airspace" (i.e. the prism over the polygons with height `walkableClimb`), marked grey, is closer than anything outside:
grafik

---

I'm personally only interested in the red case for now, because in RTS-style games, players often give move orders with a position slightly outside the nav-mesh, and this should be snapped to the nearest nav-mesh for some tolerance.

So yes, you're right that exposing the distance might not be necessary, as it could be inferred from `isOverPoly` and `nearestPt`. However, one would get different results without knowing the implementation, as the `walkableClimb` prism is not documented.

I'm OK either way (exposing the distance or not), however it might make sense to document how the nearest point is found. I didn't know about the prism until I looked at the code, and was indeed assuming euclidean point-polygon distance.

**Comment by jakobbotsch** [comment]
I think we should remove the distance since it is not exactly the distance one might expect, so it leads to confusion. And in this case, the user can easily compute the value they want.

**Comment by Bromeon** [comment]
Removed `distance` parameter. Let me know if it's good like this, or if `isOverPoly` should now simply be a default parameter (instead of an overload).

Btw, the CI failed on Mac OS with:
```
Error: sdl2: no bottle available!

You can try to install from source with:
  brew install --build-from-source sdl2```

**Comment by jakobbotsch** [comment]
Thank you!
> Btw, the CI failed on Mac OS with:

Hmm yes, I will have to take a look at this at some point.

**Pull request merged**
