### PR TITLE
Better documentation for a few private fields in dtCrowdAgent

### PR DESCRIPTION
**Pull request by grahamboree**
as discussed in #110.

### CODE REVIEW

**Comment by leif81** [comment]
This looks like a dupe of #83

**Comment by Kromster80** [comment]
@leif81 With a slight difference. I have stumbled upon this 2 times and both times made a PR xD

**Comment by grahamboree** [comment]
I added some changes from #83 since they look like a good addition as well.  Good catch @leif81! :smile:

**Comment by Janiels** [comment]
The changes LGTM. Can you squash the commits?

**Comment by grahamboree** [comment]
Squashed. :smile:

**Pull request merged**
